### PR TITLE
Smooth scroll option, Callback functions, optional title and offset for fixed headers

### PR DESCRIPTION
**Pull request by mikelgmh**
## What?
- Added an option to enable the smooth scrolling
- Added two callback options. One fires before the scroll starts, the other one fires after the scroll ends.
- Changed the heading property. Now the heading property is an optional object.
- Added an option to add an offset for sticky headers.
- Updated readme with the new changes.

## Why?
Extends and improves the utility of this script. Why use Javascript instead of pure CSS to scroll smoothly? Because I find this way easier to get this to work with a sticky navbar, as the contents might be hidden behind the navbar.
## How?
This includes changes in the js file, and some other small changes in the HTML and readme.
## Testing?
Locally

### CODE REVIEW

**Comment by cferdinandi** [comment]
I really like the idea of making the heading optional, but smooth scrolling is, IMO, best handled with CSS instead of JS these days: https://gomakethings.com/smooth-scrolling-links-with-only-css/

Accordingly, I'm not in favor of adding that feature, and think that before/after callbacks are probably unneeded for what this script is.

**Comment by mikelgmh** [comment]
@cferdinandi Yes, the smooth scrolling should be handled with CSS insead of JS, but the explanation is that this won't work properly for pages with sticky navbars, as the target element might be hidden under the sticky navbar. That's why I added the `headerOffset` property 🙂

**Comment by cferdinandi** [comment]
@mikelgmh There's actually a CSS property for that, too: https://gomakethings.com/how-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header-with-one-line-of-css/

**Comment by mikelgmh** [comment]
> @mikelgmh There's actually a CSS property for that, too: https://gomakethings.com/how-to-prevent-anchor-links-from-scrolling-behind-a-sticky-header-with-one-line-of-css/

I didn't know about this CSS property, thank you!

**Pull request closed without merging**
